name: Push to Github registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
        
     - name: Log in to the Container registry
       uses: docker/login-action@1f36f5b7a2d2f7bfd524795fc966e6d88c37baa9
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Build and push Docker image
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: ghcr.io/qjoly/simpledebianrepository
